name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.manymobs.ManyMobs
version: ${version}
api-version: 1.13

commands:
  manymobs:
    description: Main command for ManyMobs
    aliases:
      - mobs
      - spawnmany
      - summonmany
    permission: manymobs.command

permissions:
  manymobs.command:
    description: Allows the player to use /manymobs
